// <auto-generated />
using System;
using JsonParser.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JsonParser.Persistence.Migrations
{
    [DbContext(typeof(ParseJsonDbContext))]
    [Migration("20250211205913_Delete_NotNullConstraint_Company")]
    partial class Delete_NotNullConstraint_Company
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("JsonParser.Domain.Entity.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("registration_date");

                    b.HasKey("Id");

                    b.ToTable("company", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
