// <auto-generated />
using System;
using JsonParser.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JsonParser.Persistence.Migrations
{
    [DbContext(typeof(ParseJsonDbContext))]
    [Migration("20250212150327_AddReferences_ConstructionObject_ToAllEntities")]
    partial class AddReferences_ConstructionObject_ToAllEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("JsonParser.Domain.Entit.Knot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ObjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId");

                    b.HasIndex("ReferenceId");

                    b.ToTable("Knot", (string)null);
                });

            modelBuilder.Entity("JsonParser.Domain.Entity.ConstructionObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BeIncomingConfirmation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BeOutgoingConfirmation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BeProcessedApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BinaryData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateRegistration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPushed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetaCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConstructionObject", (string)null);
                });

            modelBuilder.Entity("JsonParser.Domain.Entity.MessageFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ObjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("JsonParser.Domain.Entity.Reference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ObjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId");

                    b.ToTable("Reference", (string)null);
                });

            modelBuilder.Entity("JsonParser.Domain.Entit.Knot", b =>
                {
                    b.HasOne("JsonParser.Domain.Entity.ConstructionObject", "ConstructionObject")
                        .WithMany("Knotes")
                        .HasForeignKey("ObjectId");

                    b.HasOne("JsonParser.Domain.Entity.Reference", "Reference")
                        .WithMany("Knotes")
                        .HasForeignKey("ReferenceId");

                    b.Navigation("ConstructionObject");

                    b.Navigation("Reference");
                });

            modelBuilder.Entity("JsonParser.Domain.Entity.MessageFormat", b =>
                {
                    b.HasOne("JsonParser.Domain.Entity.ConstructionObject", "ConstructionObject")
                        .WithMany("MessageFormats")
                        .HasForeignKey("ObjectId");

                    b.Navigation("ConstructionObject");
                });

            modelBuilder.Entity("JsonParser.Domain.Entity.Reference", b =>
                {
                    b.HasOne("JsonParser.Domain.Entity.ConstructionObject", "ConstructionObject")
                        .WithMany("References")
                        .HasForeignKey("ObjectId");

                    b.Navigation("ConstructionObject");
                });

            modelBuilder.Entity("JsonParser.Domain.Entity.ConstructionObject", b =>
                {
                    b.Navigation("Knotes");

                    b.Navigation("MessageFormats");

                    b.Navigation("References");
                });

            modelBuilder.Entity("JsonParser.Domain.Entity.Reference", b =>
                {
                    b.Navigation("Knotes");
                });
#pragma warning restore 612, 618
        }
    }
}
